In [49]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\admin\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: bleach in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.30 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (0.1.30)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\admin\anaconda3\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\admin\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\admin\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\admin\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\admin\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\admin\anaconda3\lib\site-packages (from requests->kaggle) (2025.11.12)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [50]:
!kaggle competitions download -c playground-series-s4e3

playground-series-s4e3.zip: Skipping, found more recently modified local copy (use --force to force download)

In [51]:
import zipfile

zip_path = "playground-series-s4e3.zip"
extract_path = "playground-series-s4e3"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [52]:
import pandas as pd
loc=extract_path + '/' + "train.csv"
df = pd.read_csv(loc)
df.head()

,id,X_Minimum,X_Maximum,Y_Minimum,Y_Maximum,Pixels_Areas,X_Perimeter,Y_Perimeter,Sum_of_Luminosity,Minimum_of_Luminosity,...,Orientation_Index,Luminosity_Index,SigmoidOfAreas,Pastry,Z_Scratch,K_Scatch,Stains,Dirtiness,Bumps,Other_Faults
0,0,584,590,909972,909977,16,8,5,2274,113,...,-0.5000,-0.0104,0.1417,0,0,0,1,0,0,0
1,1,808,816,728350,728372,433,20,54,44478,70,...,0.7419,-0.2997,0.9491,0,0,0,0,0,0,1
2,2,39,192,2212076,2212144,11388,705,420,1311391,29,...,-0.0105,-0.0944,1.0000,0,0,1,0,0,0,0
3,3,781,789,3353146,3353173,210,16,29,3202,114,...,0.6667,-0.0402,0.4025,0,0,1,0,0,0,0
4,4,1540,1560,618457,618502,521,72,67,48231,82,...,0.9158,-0.2455,0.9998,0,0,0,0,0,0,1

In [53]:

def negligible_category(df):
    # 1. Compute the Pearson Correlation matrix
    corr_df = df.corr(method="pearson")
    cols = list(corr_df.columns)
    
    # Lists to store the filtered pairs and values
    pairs_list = []
    corr_value = []
    
    # 2. Loop through the lower triangle of the correlation matrix to avoid duplicates
    for i in range(1, len(cols), 1):
        for j in range(0, i, 1):
            val = corr_df[cols[i]][cols[j]]
            # Check if absolute correlation is between 0 and 0.2
            if (abs(val) >= 0) and (abs(val) < 0.2):
                pairs_list.append(f"{cols[i]} vs {cols[j]}")
                corr_value.append(val)
                
    # 3. Create the output summary DataFrame
    negligible_df = pd.DataFrame()
    negligible_df["Entity"] = pairs_list
    negligible_df["Correlation Coefficient"] = corr_value
    
    return negligible_df

# 4. Call the function on your loaded DataFrame
# Make sure your 'df' is loaded (e.g., df = pd.read_csv("your_file.csv"))
result_df = negligible_category(df)
result_df

                               Entity  Correlation Coefficient
0                     X_Minimum vs id                 0.004657
1                     X_Maximum vs id                 0.004406
2                     Y_Minimum vs id                -0.007632
3              Y_Minimum vs X_Minimum                 0.016071
4              Y_Minimum vs X_Maximum                 0.018909
..                                ...                      ...
353  Other_Faults vs Luminosity_Index                 0.037015
354    Other_Faults vs SigmoidOfAreas                -0.129298
355         Other_Faults vs Z_Scratch                -0.181566
356            Other_Faults vs Stains                -0.125596
357         Other_Faults vs Dirtiness                -0.115800

[358 rows x 2 columns]

In [54]:
def weak_category(df):
    # 1. Compute the Pearson Correlation matrix
    corr_df = df.corr(method="pearson")
    cols = list(corr_df.columns)
    
    # Storage lists for filtered feature combinations and coefficients
    pairs_list = []
    corr_value = []
    
    # 2. Iterate across unique column pairings (lower triangular half)
    for i in range(1, len(cols), 1):
        for j in range(0, i, 1):
            val = corr_df[cols[i]][cols[j]]
            # Filter condition: absolute correlation between 0.2 and 0.4
            if (abs(val) >= 0.2) and (abs(val) < 0.4):
                pairs_list.append(f"{cols[i]} vs {cols[j]}")
                corr_value.append(val)
                
    # 3. Structuralize outcomes into a result DataFrame
    weak_df = pd.DataFrame()
    weak_df["Entity"] = pairs_list
    weak_df["Correlation Coefficient"] = corr_value
    
    return weak_df

# 4. Execute the function on your dataset
result_weak_df = weak_category(df)
result_weak_df

                                    Entity  Correlation Coefficient
0                Pixels_Areas vs X_Maximum                -0.391937
1                 X_Perimeter vs X_Maximum                -0.378434
2                 Y_Perimeter vs X_Maximum                -0.356528
3           Sum_of_Luminosity vs X_Maximum                -0.363092
4       Minimum_of_Luminosity vs X_Minimum                 0.337748
..                                     ...                      ...
129  Other_Faults vs Steel_Plate_Thickness                 0.202910
130        Other_Faults vs Outside_X_Index                -0.215491
131            Other_Faults vs Log_X_Index                -0.202018
132                 Other_Faults vs Pastry                -0.206815
133               Other_Faults vs K_Scatch                -0.330406

[134 rows x 2 columns]

In [55]:

def moderate_category(df):
    # 1. Compute the Pearson Correlation matrix
    corr_df = df.corr(method="pearson")
    cols = list(corr_df.columns)
    
    # Storage lists for filtered feature combinations and coefficients
    pairs_list = []
    corr_value = []
    
    # 2. Iterate across unique column pairings (lower triangular half)
    for i in range(1, len(cols), 1):
        for j in range(0, i, 1):
            val = corr_df[cols[i]][cols[j]]
            # Filter condition: absolute correlation between 0.4 and 0.6
            if (abs(val) >= 0.4) and (abs(val) < 0.6):
                pairs_list.append(f"{cols[i]} vs {cols[j]}")
                corr_value.append(val)
                
    # 3. Structuralize outcomes into a result DataFrame
    moderate_df = pd.DataFrame()
    moderate_df["Entity"] = pairs_list
    moderate_df["Correlation Coefficient"] = corr_value
    
    return moderate_df

# 4. Execute the function on your dataset
result_moderate_df = moderate_category(df)
result_moderate_df

                                        Entity  Correlation Coefficient
0                    Pixels_Areas vs X_Minimum                -0.464759
1                     X_Perimeter vs X_Minimum                -0.451961
2                     Y_Perimeter vs X_Minimum                -0.426514
3               Sum_of_Luminosity vs X_Minimum                -0.430073
4   Minimum_of_Luminosity vs Sum_of_Luminosity                -0.580857
5       TypeOfSteel_A300 vs Length_of_Conveyer                 0.434913
6       TypeOfSteel_A400 vs Length_of_Conveyer                -0.433691
7                 Outside_X_Index vs X_Minimum                -0.522112
8                 Outside_X_Index vs X_Maximum                -0.432545
9                 Edges_X_Index vs Y_Perimeter                -0.469092
10                  Edges_Y_Index vs X_Minimum                 0.460421
11      Edges_Y_Index vs Minimum_of_Luminosity                 0.467841
12                Edges_Y_Index vs Empty_Index                -0.465523
13       Outside_Global_Index vs Edges_Y_Index                 0.529914
14                     LogOfAreas vs X_Minimum                -0.505024
15                     LogOfAreas vs X_Maximum                -0.428875
16                   LogOfAreas vs Edges_Index                -0.420367
17                 LogOfAreas vs Edges_X_Index                -0.462665
18                    Log_X_Index vs X_Minimum                -0.530728
19                    Log_X_Index vs X_Maximum                -0.448348
20                  Log_X_Index vs Empty_Index                 0.421585
21         Log_X_Index vs Outside_Global_Index                -0.436422
22        Log_Y_Index vs Minimum_of_Luminosity                -0.585194
23              Log_Y_Index vs Outside_X_Index                 0.598918
24                Log_Y_Index vs Edges_Y_Index                -0.464314
25        Orientation_Index vs Outside_X_Index                -0.467688
26          Orientation_Index vs Edges_X_Index                -0.412696
27            Orientation_Index vs Log_X_Index                -0.520981
28              SigmoidOfAreas vs Pixels_Areas                 0.542672
29               SigmoidOfAreas vs X_Perimeter                 0.561256
30         SigmoidOfAreas vs Sum_of_Luminosity                 0.520282
31     SigmoidOfAreas vs Minimum_of_Luminosity                -0.504692
32               SigmoidOfAreas vs Empty_Index                 0.480116
33             SigmoidOfAreas vs Edges_X_Index                -0.538678
34             SigmoidOfAreas vs Edges_Y_Index                -0.594737
35                       K_Scatch vs X_Minimum                -0.510597
36                       K_Scatch vs X_Maximum                -0.441177
37           K_Scatch vs Minimum_of_Luminosity                -0.586957
38                     K_Scatch vs Log_Y_Index                 0.546596
39               K_Scatch vs Orientation_Index                -0.414475
40                  K_Scatch vs SigmoidOfAreas                 0.532203
41                       Other_Faults vs Bumps                -0.413112

In [56]:

def strong_category(df):
    corr_df = df.corr(method="pearson")
    cols = list(corr_df.columns)
    
    # Renamed variable to avoid conflict with the function name
    strong_pairs, corr_value = [], []
    
    for i in range(1, len(cols)):
        for j in range(0, i):
            val = corr_df[cols[i]][cols[j]]
            if 0.6 <= abs(val) < 0.8:
                strong_pairs.append(f"{cols[i]} vs {cols[j]}")
                corr_value.append(val)
                
    strong_df = pd.DataFrame()
    strong_df["Entity"] = strong_pairs
    strong_df["Correlation Coefficient"] = corr_value
    
    return strong_df
    strong_category(df)

In [57]:
 strong_category(df)

                                       Entity  Correlation Coefficient
0           Sum_of_Luminosity vs Pixels_Areas                 0.797843
1       Minimum_of_Luminosity vs Pixels_Areas                -0.622867
2        Minimum_of_Luminosity vs X_Perimeter                -0.603891
3        Minimum_of_Luminosity vs Y_Perimeter                -0.602826
4             Outside_X_Index vs Pixels_Areas                 0.764810
5              Outside_X_Index vs X_Perimeter                 0.752470
6              Outside_X_Index vs Y_Perimeter                 0.700036
7        Outside_X_Index vs Sum_of_Luminosity                 0.703912
8    Outside_X_Index vs Minimum_of_Luminosity                -0.638549
9               Edges_Y_Index vs Pixels_Areas                -0.650704
10               Edges_Y_Index vs X_Perimeter                -0.664781
11               Edges_Y_Index vs Y_Perimeter                -0.612157
12         Edges_Y_Index vs Sum_of_Luminosity                -0.608297
13           Edges_Y_Index vs Outside_X_Index                -0.760021
14                 LogOfAreas vs Pixels_Areas                 0.774580
15                  LogOfAreas vs X_Perimeter                 0.771546
16                  LogOfAreas vs Y_Perimeter                 0.790863
17            LogOfAreas vs Sum_of_Luminosity                 0.726483
18        LogOfAreas vs Minimum_of_Luminosity                -0.691406
19                LogOfAreas vs Edges_Y_Index                -0.713607
20                Log_X_Index vs Pixels_Areas                 0.749731
21                 Log_X_Index vs X_Perimeter                 0.750418
22                 Log_X_Index vs Y_Perimeter                 0.705657
23           Log_X_Index vs Sum_of_Luminosity                 0.698035
24       Log_X_Index vs Minimum_of_Luminosity                -0.637711
25                Log_Y_Index vs Pixels_Areas                 0.640033
26                 Log_Y_Index vs X_Perimeter                 0.667441
27                 Log_Y_Index vs Y_Perimeter                 0.761117
28           Log_Y_Index vs Sum_of_Luminosity                 0.615651
29               Log_Y_Index vs Edges_X_Index                -0.651384
30                 Log_Y_Index vs Log_X_Index                 0.667899
31         Orientation_Index vs Edges_Y_Index                 0.607271
32  Luminosity_Index vs Minimum_of_Luminosity                 0.619174
33              SigmoidOfAreas vs Y_Perimeter                 0.608167
34          SigmoidOfAreas vs Outside_X_Index                 0.609049
35              SigmoidOfAreas vs Log_X_Index                 0.748741
36                   K_Scatch vs Pixels_Areas                 0.701014
37                    K_Scatch vs X_Perimeter                 0.675056
38                    K_Scatch vs Y_Perimeter                 0.630270
39              K_Scatch vs Sum_of_Luminosity                 0.640597
40                K_Scatch vs Outside_X_Index                 0.778859
41                  K_Scatch vs Edges_Y_Index                -0.678464
42                     K_Scatch vs LogOfAreas                 0.745533
43                    K_Scatch vs Log_X_Index                 0.782110

In [58]:

def very_strong_category(df):
    corr_df = df.corr(method="pearson")
    cols = list(corr_df.columns)
    
    # Renamed variable to avoid conflict with the function name
    very_strong_pairs, corr_value = [], []
    
    for i in range(1, len(cols)):
        for j in range(0, i):
            val = corr_df[cols[i]][cols[j]]
            # Filter condition: absolute correlation greater than or equal to 0.8
            if abs(val) >= 0.8:
                very_strong_pairs.append(f"{cols[i]} vs {cols[j]}")
                corr_value.append(val)
                
    very_strong_df = pd.DataFrame()
    very_strong_df["Entity"] = very_strong_pairs
    very_strong_df["Correlation Coefficient"] = corr_value
    
    return very_strong_df
    strong_category(df)

In [59]:
strong_category(df)

                                       Entity  Correlation Coefficient
0           Sum_of_Luminosity vs Pixels_Areas                 0.797843
1       Minimum_of_Luminosity vs Pixels_Areas                -0.622867
2        Minimum_of_Luminosity vs X_Perimeter                -0.603891
3        Minimum_of_Luminosity vs Y_Perimeter                -0.602826
4             Outside_X_Index vs Pixels_Areas                 0.764810
5              Outside_X_Index vs X_Perimeter                 0.752470
6              Outside_X_Index vs Y_Perimeter                 0.700036
7        Outside_X_Index vs Sum_of_Luminosity                 0.703912
8    Outside_X_Index vs Minimum_of_Luminosity                -0.638549
9               Edges_Y_Index vs Pixels_Areas                -0.650704
10               Edges_Y_Index vs X_Perimeter                -0.664781
11               Edges_Y_Index vs Y_Perimeter                -0.612157
12         Edges_Y_Index vs Sum_of_Luminosity                -0.608297
13           Edges_Y_Index vs Outside_X_Index                -0.760021
14                 LogOfAreas vs Pixels_Areas                 0.774580
15                  LogOfAreas vs X_Perimeter                 0.771546
16                  LogOfAreas vs Y_Perimeter                 0.790863
17            LogOfAreas vs Sum_of_Luminosity                 0.726483
18        LogOfAreas vs Minimum_of_Luminosity                -0.691406
19                LogOfAreas vs Edges_Y_Index                -0.713607
20                Log_X_Index vs Pixels_Areas                 0.749731
21                 Log_X_Index vs X_Perimeter                 0.750418
22                 Log_X_Index vs Y_Perimeter                 0.705657
23           Log_X_Index vs Sum_of_Luminosity                 0.698035
24       Log_X_Index vs Minimum_of_Luminosity                -0.637711
25                Log_Y_Index vs Pixels_Areas                 0.640033
26                 Log_Y_Index vs X_Perimeter                 0.667441
27                 Log_Y_Index vs Y_Perimeter                 0.761117
28           Log_Y_Index vs Sum_of_Luminosity                 0.615651
29               Log_Y_Index vs Edges_X_Index                -0.651384
30                 Log_Y_Index vs Log_X_Index                 0.667899
31         Orientation_Index vs Edges_Y_Index                 0.607271
32  Luminosity_Index vs Minimum_of_Luminosity                 0.619174
33              SigmoidOfAreas vs Y_Perimeter                 0.608167
34          SigmoidOfAreas vs Outside_X_Index                 0.609049
35              SigmoidOfAreas vs Log_X_Index                 0.748741
36                   K_Scatch vs Pixels_Areas                 0.701014
37                    K_Scatch vs X_Perimeter                 0.675056
38                    K_Scatch vs Y_Perimeter                 0.630270
39              K_Scatch vs Sum_of_Luminosity                 0.640597
40                K_Scatch vs Outside_X_Index                 0.778859
41                  K_Scatch vs Edges_Y_Index                -0.678464
42                     K_Scatch vs LogOfAreas                 0.745533
43                    K_Scatch vs Log_X_Index                 0.782110