In [5]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

In [6]:
# Define the file path location
loc = "playground-series-s4e11" + "/" + "train.csv"

# Load the dataset into a pandas DataFrame
df = pd.read_csv(loc)

# Display the first few rows to verify loading
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [7]:
# 3.2 Simple Random Sampling without Replacement
sample_size = 15

# Corrected typo from 'randoe' to 'random'
sample_2 = np.random.choice(df["Name"], size=sample_size, replace=False)
sample_2

array(['Abhishek', 'Aanchal', 'Aniket', 'Gagan', 'Mahi', 'Saurav', 'Vani',
       'Ishaani', 'Palak', 'Pihu', 'Aniket', 'Rohan', 'Shivam', 'Kartik',
       'Rishi'], dtype=object)

In [8]:
# 2. Systematic Random Sampling
sample_size = 50

# Calculate the interval step (k)
interval = len(df["Name"]) // sample_size
sample = []

# Select every kth entry from the Name column
for x in range(0, len(df["Name"]), interval):
    # If this throws a KeyError later, change df["Name"][x] to df["Name"].iloc[x]
    sample.append(df["Name"][x])

print(sample)

['Aaradhya', 'Veda', 'Parth', 'Advait', 'Rohan', 'Vivaan', 'Ira', 'Aarush', 'Aryan', 'Vibha', 'Rishi', 'Ritvik', 'Advait', 'Ishwar', 'Harsha', 'Manan', 'Bhavesh', 'Ritika', 'Ansh', 'Pratham', 'Nikita', 'Aditi', 'Harsha', 'Pallavi', 'Tara', 'Vivan', 'Neha', 'Aniket', 'Rashi', 'Advait', 'Rupak', 'Raunak', 'Veda', 'Rupak', 'Barkha', 'Mayank', 'Rohan', 'Rupak', 'Aarya', 'Siddhesh', 'Prisha', 'Aditya', 'Aaradhya', 'Aariv', 'Rahil', 'Janvi', 'Simran', 'Rishi', 'Ritik', 'Gauri']

In [9]:
# # Stratified Random Sampling
# Assuming 'Gender' is the column used for stratification
sample_size_of_each_strata = 500
category_column = df["Gender"]
category = category_column.value_counts().index
sample_df = pd.DataFrame()

for x in category:
    filtered_df = df[category_column == x]
    
    # Corrected 'randos.choice' to 'random.choice'
    random_index = np.random.choice(
        filtered_df.index, 
        size=sample_size_of_each_strata, 
        replace=False
    )
    
    # Corrected indent to keep it inside the loop block
    sample_df = pd.concat([sample_df, df.loc[random_index]])

# Reset the index of the final combined dataframe
sample_df.reset_index(inplace=True, drop=True)

In [10]:
sample_df

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,95055,Samar,Male,38.0,Srinagar,Working Professional,Content Writer,NaN,4.0,NaN,NaN,5.0,7-8 hours,Unhealthy,M.Ed,No,4.0,4.0,Yes,0
1,7499,Ansh,Male,60.0,Kalyan,Working Professional,Teacher,NaN,1.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,BCA,Yes,2.0,4.0,Yes,0
2,98164,Aariv,Male,54.0,Hyderabad,Working Professional,Content Writer,NaN,1.0,NaN,NaN,2.0,More than 8 hours,Moderate,ME,Yes,9.0,1.0,Yes,0
3,18165,Abhishek,Male,36.0,Surat,Working Professional,Doctor,NaN,4.0,NaN,NaN,4.0,Less than 5 hours,Unhealthy,M.Pharm,No,10.0,2.0,Yes,0
4,46950,Shaurya,Male,38.0,Kanpur,Working Professional,Researcher,NaN,5.0,NaN,NaN,4.0,7-8 hours,Unhealthy,B.Tech,No,3.0,5.0,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,41988,Aanchal,Female,24.0,Agra,Student,NaN,3.0,NaN,9.93,2.0,NaN,5-6 hours,Moderate,B.Pharm,Yes,12.0,1.0,No,1
996,114179,Ritika,Female,36.0,Mumbai,Working Professional,Data Scientist,NaN,3.0,NaN,NaN,4.0,5-6 hours,Moderate,MCA,No,5.0,4.0,Yes,0
997,40971,Kashish,Female,20.0,Ludhiana,Student,NaN,4.0,NaN,5.32,1.0,NaN,Less than 5 hours,Unhealthy,Class 12,Yes,1.0,3.0,No,1
998,21646,Vani,Female,26.0,Thane,Working Professional,Content Writer,NaN,4.0,NaN,NaN,4.0,7-8 hours,Moderate,M.Tech,No,8.0,3.0,No,1
999,4393,Zara,Female,48.0,Ahmedabad,Working Professional,Entrepreneur,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Unhealthy,MSc,No,1.0,2.0,Yes,0

In [11]:
# Step 6: Verify the stratification counts
sample_df["Gender"].value_counts()

Gender
Male      500
Female    500
Name: count, dtype: int64

In [12]:
# # Cluster Random Sampling
# Assuming 'Working Professional or Student' is the column used for Clustering
sample_size_of_each_strata = 1000
category_column = df["Working Professional or Student"]
category = category_column.value_counts().index

# Create separate DataFrames for each cluster group
cluster_1_df = df[category_column == category[0]]
cluster_2_df = df[category_column == category[1]]

In [13]:
cluster_1_df

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0
5,5,Vani,Female,59.0,Ahmedabad,Working Professional,Finanancial Analyst,NaN,2.0,NaN,NaN,5.0,5-6 hours,Healthy,MCA,No,7.0,5.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140694,140694,Ishaani,Female,45.0,Ahmedabad,Working Professional,Teacher,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,B.Ed,Yes,1.0,5.0,No,0
140695,140695,Vidya,Female,18.0,Ahmedabad,Working Professional,NaN,NaN,5.0,NaN,NaN,4.0,5-6 hours,Unhealthy,Class 12,No,2.0,4.0,Yes,1
140696,140696,Lata,Female,41.0,Hyderabad,Working Professional,Content Writer,NaN,5.0,NaN,NaN,4.0,7-8 hours,Moderate,B.Tech,Yes,6.0,5.0,Yes,0
140697,140697,Aanchal,Female,24.0,Kolkata,Working Professional,Marketing Manager,NaN,3.0,NaN,NaN,1.0,More than 8 hours,Moderate,B.Com,No,4.0,4.0,No,0
140698,140698,Prachi,Female,49.0,Srinagar,Working Professional,Plumber,NaN,5.0,NaN,NaN,2.0,5-6 hours,Moderate,ME,Yes,10.0,1.0,No,0

In [1]:
import pandas as pd
import numpy as np

loc = "playground-series-s4e11" + "/" + "train.csv"

# Load the dataset into a pandas DataFrame
df = pd.read_csv(loc)

# Display the first few rows to verify loading
df.head()


# Simple Random Sampling
print(np.random.choice(df["Name"], 15, replace=True))
print(np.random.choice(df["Name"], 15, replace=False))

# Systematic Sampling
interval = len(df) // 50
print(df["Name"][::interval][:50].tolist())

# Stratified Sampling
sample_df = df.groupby("Gender", group_keys=False).sample(n=500)
print(sample_df["Gender"].value_counts())

# Cluster Sampling
cluster = df["Working Professional or Student"].unique()
cluster_df = df[df["Working Professional or Student"] == cluster[0]]
print(cluster_df)

['Keshav' 'Rahil' 'Pallavi' 'Jhanvi' 'Bhavesh' 'Shlok' 'Reyansh' 'Rashi'
 'Nirvaan' 'Veda' 'Harshil' 'Aishwarya' 'Riya' 'Krishna' 'Ila']
['Ishan' 'Shivam' 'Ishan' 'Ranveer' 'Chhavi' 'Rupak' 'Tanmay' 'Anirudh'
 'Tushar' 'Ishan' 'Vikram' 'Ila' 'Hrithik' 'Prachi' 'Jasmine']
['Aaradhya', 'Veda', 'Parth', 'Advait', 'Rohan', 'Vivaan', 'Ira', 'Aarush', 'Aryan', 'Vibha', 'Rishi', 'Ritvik', 'Advait', 'Ishwar', 'Harsha', 'Manan', 'Bhavesh', 'Ritika', 'Ansh', 'Pratham', 'Nikita', 'Aditi', 'Harsha', 'Pallavi', 'Tara', 'Vivan', 'Neha', 'Aniket', 'Rashi', 'Advait', 'Rupak', 'Raunak', 'Veda', 'Rupak', 'Barkha', 'Mayank', 'Rohan', 'Rupak', 'Aarya', 'Siddhesh', 'Prisha', 'Aditya', 'Aaradhya', 'Aariv', 'Rahil', 'Janvi', 'Simran', 'Rishi', 'Ritik', 'Gauri']
Gender
Female    500
Male      500
Name: count, dtype: int64
            id      Name  Gender   Age       City  \
0            0  Aaradhya  Female  49.0   Ludhiana
1            1     Vivan    Male  26.0   Varanasi
3            3    Yuvraj    Male  22.0     Mumbai
4            4      Rhea  Female  30.0     Kanpur
5            5      Vani  Female  59.0  Ahmedabad
...        ...       ...     ...   ...        ...
140694  140694   Ishaani  Female  45.0  Ahmedabad
140695  140695     Vidya  Female  18.0  Ahmedabad
140696  140696      Lata  Female  41.0  Hyderabad
140697  140697   Aanchal  Female  24.0    Kolkata
140698  140698    Prachi  Female  49.0   Srinagar

       Working Professional or Student           Profession  \
0                 Working Professional                 Chef
1                 Working Professional              Teacher
3                 Working Professional              Teacher
4                 Working Professional     Business Analyst
5                 Working Professional  Finanancial Analyst
...                                ...                  ...
140694            Working Professional              Teacher
140695            Working Professional                  NaN
140696            Working Professional       Content Writer
140697            Working Professional    Marketing Manager
140698            Working Professional              Plumber

        Academic Pressure  Work Pressure  CGPA  Study Satisfaction  \
0                     NaN            5.0   NaN                 NaN
1                     NaN            4.0   NaN                 NaN
3                     NaN            5.0   NaN                 NaN
4                     NaN            1.0   NaN                 NaN
5                     NaN            2.0   NaN                 NaN
...                   ...            ...   ...                 ...
140694                NaN            2.0   NaN                 NaN
140695                NaN            5.0   NaN                 NaN
140696                NaN            5.0   NaN                 NaN
140697                NaN            3.0   NaN                 NaN
140698                NaN            5.0   NaN                 NaN

        Job Satisfaction     Sleep Duration Dietary Habits    Degree  \
0                    2.0  More than 8 hours        Healthy       BHM
1                    3.0  Less than 5 hours      Unhealthy       LLB
3                    1.0  Less than 5 hours       Moderate       BBA
4                    1.0          5-6 hours      Unhealthy       BBA
5                    5.0          5-6 hours        Healthy       MCA
...                  ...                ...            ...       ...
140694               5.0  Less than 5 hours       Moderate      B.Ed
140695               4.0          5-6 hours      Unhealthy  Class 12
140696               4.0          7-8 hours       Moderate    B.Tech
140697               1.0  More than 8 hours       Moderate     B.Com
140698               2.0          5-6 hours       Moderate        ME

       Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                         No               1.0
1                                        Yes               7.0
3                                        Yes              10.0
4                                        Yes               9.0
5                                         No               7.0
...                                      ...               ...
140694                                   Yes               1.0
140695                                    No               2.0
140696                                   Yes               6.0
140697                                    No               4.0
140698                                   Yes              10.0

        Financial Stress Family History of Mental Illness  Depression
0                    2.0                               No           0
1                    3.0                               No           1
3                    1.0                              Yes           1
4                    4.0                              Yes           0
5                    5.0                               No           0
...                  ...                              ...         ...
140694               5.0                               No           0
140695               4.0                              Yes           1
140696               5.0                              Yes           0
140697               4.0                               No           0
140698               1.0                               No           0

[112799 rows x 20 columns]

In [3]:
import pandas as pd
import numpy as np

loc = "playground-series-s4e11" + "/" + "train.csv"

# Load the dataset into a pandas DataFrame
df = pd.read_csv(loc)

# Display the first few rows to verify loading
df.head(15)

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0
5,5,Vani,Female,59.0,Ahmedabad,Working Professional,Finanancial Analyst,NaN,2.0,NaN,NaN,5.0,5-6 hours,Healthy,MCA,No,7.0,5.0,No,0
6,6,Ritvik,Male,47.0,Thane,Working Professional,Chemist,NaN,5.0,NaN,NaN,2.0,7-8 hours,Moderate,MD,No,6.0,2.0,No,0
7,7,Rajveer,Male,38.0,Nashik,Working Professional,Teacher,NaN,3.0,NaN,NaN,4.0,7-8 hours,Unhealthy,B.Pharm,No,10.0,3.0,Yes,0
8,8,Aishwarya,Female,24.0,Bangalore,Student,NaN,2.0,NaN,5.90,5.0,NaN,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
9,9,Simran,Female,42.0,Patna,Working Professional,Electrician,NaN,4.0,NaN,NaN,1.0,5-6 hours,Healthy,ME,Yes,7.0,2.0,Yes,0
10,10,Utkarsh,Male,55.0,Rajkot,Working Professional,Software Engineer,NaN,3.0,NaN,NaN,2.0,7-8 hours,Moderate,BSc,No,6.0,4.0,Yes,0
11,11,Aahana,Female,51.0,Patna,Working Professional,Teacher,NaN,1.0,NaN,NaN,2.0,7-8 hours,Moderate,B.Arch,No,9.0,5.0,No,0
12,12,Tejas,Male,39.0,Jaipur,Working Professional,Data Scientist,NaN,2.0,NaN,NaN,5.0,More than 8 hours,Moderate,BCA,Yes,1.0,3.0,No,0
13,13,Aadhya,Female,29.0,Pune,Working Professional,Chef,NaN,4.0,NaN,NaN,4.0,7-8 hours,Unhealthy,BHM,No,6.0,5.0,Yes,0
14,14,Kiran,Male,50.0,Thane,Working Professional,Plumber,NaN,1.0,NaN,NaN,1.0,More than 8 hours,Moderate,BE,Yes,8.0,5.0,Yes,0

In [10]:
# Simple Random Sampling
#Randomly select 15 names from the Name column-repitation allowed.
print(np.random.choice(df["Name"], 25, replace=True))

['Abhinav' 'Samaira' 'Raunak' 'Vrinda' 'Vivan' 'Zoya' 'Ira' 'Keshav'
 'Vani' 'Aarav' 'Vikram' 'Aarya' 'Naina' 'Raghavendra' 'Kunal' 'Raunak'
 'Jiya' 'Tanmay' 'Ivaan' 'Zara' 'Aaradhya' 'Pratham' 'Parth' 'Rishi'
 'Kunal']

In [8]:
#no repitation allowed
print(np.random.choice(df["Name"], 10, replace=False))

['Keshav' 'Mihir' 'Vedant' 'Kartikeya' 'Srishti' 'Aariv' 'Harshil'
 'Ishwar' 'Shaurya' 'Aarohi']

In [14]:
#Systematic Random Sampling
#Instead of randomly picking every person, you pick every fixed interval
interval = len(df) // 50
print(df["Name"][::interval][:50].tolist())

['Aaradhya', 'Veda', 'Parth', 'Advait', 'Rohan', 'Vivaan', 'Ira', 'Aarush', 'Aryan', 'Vibha', 'Rishi', 'Ritvik', 'Advait', 'Ishwar', 'Harsha', 'Manan', 'Bhavesh', 'Ritika', 'Ansh', 'Pratham', 'Nikita', 'Aditi', 'Harsha', 'Pallavi', 'Tara', 'Vivan', 'Neha', 'Aniket', 'Rashi', 'Advait', 'Rupak', 'Raunak', 'Veda', 'Rupak', 'Barkha', 'Mayank', 'Rohan', 'Rupak', 'Aarya', 'Siddhesh', 'Prisha', 'Aditya', 'Aaradhya', 'Aariv', 'Rahil', 'Janvi', 'Simran', 'Rishi', 'Ritik', 'Gauri']

In [17]:
#Stratified Random Sampling
#divide the population into groups, then randomly select people from each group.
sample_df = df.groupby("Gender", group_keys=False).sample(n=500)
print(sample_df["Gender"].value_counts())

Gender
Female    500
Male      500
Name: count, dtype: int64

In [ ]:
# Cluster Sampling
cluster = df["Working Professional or Student"].unique()
cluster_df = df[df["Working Professional or Student"] == cluster[0]]
print(cluster_df)